name: 'Docker image'

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  image:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'docker/build-push-action@v1'
        with:
          repository     : 'miniclip/gonsul'
          username       : ${{ secrets.DOCKER_USERNAME }}
          password       : ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels : true
          tag_with_ref   : true
          tag_with_sha   : true
